[package]
name = "rustmoon"
version = "0.1.0"
edition = "2021"
build = "build/build.rs"

[[bin]]
name = "lua"
test = false
bench = false

[dependencies]
libc = "0.2"
rand = "0.8.5"

[build-dependencies]
cc = "1.0"
